name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lisp: [sbcl]

    env:
      LISP: ${{ matrix.lisp }}

    steps:
      - uses: actions/checkout@v4
      - name: Build a Docker image
        run: docker build -t visualcrossing-test -f tests/Dockerfile .
      - name: Run tests
        run: docker run --rm visualcrossing-test
